### ISSUE TITLE
`create_fusion_clip` crashes script

### ISSUE THREAD

**Issue by mrhelixx** [pedrolabonia/pydavinci#23]
**Describe the bug**
It says `AttributeError: 'function' object has no attribute '_obj'` when passed a `List[TimelineItem]`

**To Reproduce**
```python
from pydavinci import davinci

resolve = davinci.Resolve()

clips = resolve.media_pool.current_folder.clips

for clip in clips:
    resolve.media_pool.create_timeline_from_clips(clip.name, [clip])
    
    timelineItems = resolve.active_timeline.items
    
    fusionClip = resolve.active_timeline.create_fusion_clip([timelineItems ])

    print(fusionClip)
```

**Expected behavior**
The fusion clip to be printed

**Screenshots**
```python
Traceback (most recent call last):
  File "C:\Users\me\AppData\Roaming\Blackmagic Design\DaVinci Resolve\Support\Fusion\Scripts\testCode.py", line 39, in <module>
    fusionClip = resolve.active_timeline.create_fusion_clip([selectedClip])
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\pydavinci\wrappers\timeline.py", line 298, in create_fusion_clip
    return TimelineItem(self._obj.CreateFusionClip(get_resolveobjs(timeline_items)))
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\pydavinci\utils.py", line 9, in get_resolveobjs
    return [x._obj for x in objs]
  File "C:\Users\me\AppData\Local\Programs\Python\Python36\lib\site-packages\pydavinci\utils.py", line 9, in <listcomp>
    return [x._obj for x in objs]
AttributeError: 'function' object has no attribute '_obj'
```

**Desktop (please complete the following information):**
 - OS: `Windows 10`
 - Python Version: `3.6.8`
 - Davinci Resolve Version: `18.0.4 BUILD 5`

**Additional context**
Sorry if I'm just missing something obvious here!  `create_fusion_clip` takes in `List[TimelineItem]`, and `timelineItems` is typeof `List[TimelineItem]`, so I figure this _should_ work.

**Comment by mrhelixx** [comment]
Solved!  I was missing the params in `active_timeline.items('video', 1)`
